#ifndef _BITMAPS_
#define _BITMAPS_

/*
 * bitmaps.h
 * Auto-generated by Plotter-Z Bitmap Editor
 * Do not remove BITMAP_START/BITMAP_END markers or JSON metadata
 */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_CART",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_CART[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 205, 186, 184, 186, 186, 202, 255,
	/* bitmap (1, 0) */ 255, 152, 173, 157, 173, 173, 173, 255,
	/* bitmap (2, 0) */ 224, 224, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_PARM",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_PARM[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 140, 181, 140, 189, 189, 189, 255,
	/* bitmap (1, 0) */ 255, 110, 164, 106, 110, 174, 174, 255,
	/* bitmap (2, 0) */ 224, 224, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_SAMPLE",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_SAMPLE[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 202, 184, 216, 234, 234, 154, 255,
	/* bitmap (1, 0) */ 255, 155, 171, 155, 187, 187, 184, 255,
	/* bitmap (2, 0) */ 224, 224, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_WIN",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_WIN[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 186, 187, 171, 171, 171, 214, 255,
	/* bitmap (1, 0) */ 255, 46, 102, 106, 108, 110, 46, 255,
	/* bitmap (2, 0) */ 224, 224, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_PLOT",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_PLOT[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 128, 178, 170, 178, 162, 162, 163,
	/* bitmap (1, 0) */ 255, 0, 19, 41, 41, 41, 41, 145,
	/* bitmap (2, 0) */ 224, 0, 128, 0, 0, 0, 0, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_BACK",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_BACK[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 157, 170, 152, 170, 170, 154, 255,
	/* bitmap (1, 0) */ 255, 202, 186, 185, 186, 186, 202, 255,
	/* bitmap (2, 0) */ 224, 224, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_OK",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_OK[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 249, 246, 246, 246, 246, 249, 255,
	/* bitmap (1, 0) */ 255, 183, 175, 159, 175, 183, 183, 255,
	/* bitmap (2, 0) */ 224, 224, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_HELP",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_HELP[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 168, 171, 136, 171, 171, 168, 255,
	/* bitmap (1, 0) */ 255, 185, 186, 185, 187, 187, 139, 255,
	/* bitmap (2, 0) */ 224, 224, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_EDIT",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_EDIT[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 137, 186, 138, 186, 186, 137, 255,
	/* bitmap (1, 0) */ 255, 136, 221, 221, 221, 221, 141, 255,
	/* bitmap (2, 0) */ 224, 224, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_CLEAR",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_CLEAR[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 128, 157, 161, 161, 161, 161, 157,
	/* bitmap (1, 0) */ 255, 0, 14, 9, 14, 9, 9, 233,
	/* bitmap (2, 0) */ 224, 0, 0, 0, 0, 0, 0, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_BOX",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_BOX[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 128, 184, 165, 185, 165, 165, 184,
	/* bitmap (1, 0) */ 255, 0, 200, 37, 34, 37, 40, 200,
	/* bitmap (2, 0) */ 224, 0, 128, 0, 0, 0, 128, 128
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_AXES",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_AXES[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 128, 146, 170, 185, 170, 170, 170,
	/* bitmap (1, 0) */ 255, 0, 185, 162, 57, 160, 160, 187,
	/* bitmap (2, 0) */ 224, 0, 128, 0, 0, 128, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_HIDE",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_HIDE[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 128, 171, 169, 185, 169, 169, 171,
	/* bitmap (1, 0) */ 255, 0, 179, 42, 43, 42, 42, 179,
	/* bitmap (2, 0) */ 224, 0, 128, 0, 128, 0, 0, 128
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_RESET",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_RESET[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 128, 184, 165, 184, 164, 164, 165,
	/* bitmap (1, 0) */ 255, 0, 239, 2, 194, 34, 34, 194,
	/* bitmap (2, 0) */ 224, 0, 128, 0, 0, 0, 0, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_O_P_SWITCH",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_O_P_SWITCH[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 128, 176, 169, 179, 161, 160, 160,
	/* bitmap (1, 0) */ 255, 0, 144, 9, 253, 9, 145, 0,
	/* bitmap (2, 0) */ 224, 0, 128, 64, 64, 64, 64, 128
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_PLAY",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_PLAY[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 128, 178, 170, 178, 162, 162, 163,
	/* bitmap (1, 0) */ 255, 0, 18, 42, 57, 41, 41, 169,
	/* bitmap (2, 0) */ 224, 0, 128, 128, 0, 0, 0, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_INIT",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_INIT[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 139, 217, 218, 219, 219, 139, 255,
	/* bitmap (1, 0) */ 255, 68, 110, 110, 110, 110, 70, 255,
	/* bitmap (2, 0) */ 224, 96, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_NEXT",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_NEXT[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 128, 165, 181, 172, 165, 165, 128,
	/* bitmap (1, 0) */ 255, 0, 93, 73, 137, 73, 73, 0,
	/* bitmap (2, 0) */ 224, 0, 128, 64, 32, 64, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_STOP",
   "width": 40,
   "height": 8
 }
*/

static const unsigned char MENU_STOP[] = {
	/* width */ 40, /* height */ 8,
	/* bitmap (0, 0) */ 255, 227, 221, 186, 182, 174, 221, 227,
	/* bitmap (1, 0) */ 255, 128, 136, 149, 157, 149, 149, 148,
	/* bitmap (2, 0) */ 255, 0, 193, 26, 25, 0, 24, 219,
	/* bitmap (3, 0) */ 255, 0, 185, 18, 18, 146, 146, 17,
	/* bitmap (4, 0) */ 255, 0, 48, 168, 176, 160, 160, 32
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_X_EQ",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_X_EQ[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 221, 235, 247, 235, 221, 221, 255,
	/* bitmap (1, 0) */ 255, 255, 135, 255, 255, 135, 255, 255,
	/* bitmap (2, 0) */ 224, 224, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_Y_EQ",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_Y_EQ[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 221, 235, 247, 247, 247, 247, 255,
	/* bitmap (1, 0) */ 255, 255, 135, 255, 255, 135, 255, 255,
	/* bitmap (2, 0) */ 224, 224, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_Z_EQ",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_Z_EQ[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 193, 251, 247, 239, 223, 193, 255,
	/* bitmap (1, 0) */ 255, 255, 135, 255, 255, 135, 255, 255,
	/* bitmap (2, 0) */ 224, 224, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "SPRITE_BUSY",
   "width": 8,
   "height": 8
 }
*/

static const unsigned char SPRITE_BUSY[] = {
	/* width */ 8, /* height */ 8,
	/* bitmap (0, 0) */ 15, 15, 15, 15, 0, 0, 0, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "ICON_16",
   "width": 16,
   "height": 16
 }
*/

static const unsigned char ICON_16[] = {
	/* width */ 16, /* height */ 16,
	/* bitmap (0, 0) */ 7, 24, 96, 129, 70, 32, 16, 16,
	/* bitmap (1, 0) */ 128, 64, 32, 144, 147, 143, 142, 156,
	/* bitmap (0, 1) */ 9, 9, 9, 25, 60, 60, 30, 7,
	/* bitmap (1, 1) */ 56, 116, 100, 130, 1, 6, 28, 248
};

/* #BITMAP_END */

#endif /* _BITMAPS_ */