#ifndef _BITMAPS_
#define _BITMAPS_

/*
 * bitmaps.h
 * Auto-generated by Plotter-Z Bitmap Editor
 * Do not remove BITMAP_START/BITMAP_END markers or JSON metadata
 */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_EXPR",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_EXPR[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 138, 186, 141, 186, 186, 138, 255,
	/* bitmap (1, 0) */ 255, 153, 170, 153, 186, 186, 186, 255,
	/* bitmap (2, 0) */ 224, 224, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_SAMPLE",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_SAMPLE[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 202, 184, 216, 234, 234, 154, 255,
	/* bitmap (1, 0) */ 255, 155, 171, 155, 187, 187, 184, 255,
	/* bitmap (2, 0) */ 224, 224, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_WIN",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_WIN[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 186, 187, 171, 171, 171, 214, 255,
	/* bitmap (1, 0) */ 255, 46, 102, 106, 108, 110, 46, 255,
	/* bitmap (2, 0) */ 224, 224, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_PLOT",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_PLOT[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 155, 171, 155, 187, 187, 184, 255,
	/* bitmap (1, 0) */ 255, 216, 173, 173, 173, 173, 221, 255,
	/* bitmap (2, 0) */ 224, 224, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_BACK",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_BACK[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 157, 170, 152, 170, 170, 154, 255,
	/* bitmap (1, 0) */ 255, 202, 186, 185, 186, 186, 202, 255,
	/* bitmap (2, 0) */ 224, 224, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_OK",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_OK[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 249, 246, 246, 246, 246, 249, 255,
	/* bitmap (1, 0) */ 255, 183, 175, 159, 175, 183, 183, 255,
	/* bitmap (2, 0) */ 224, 224, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_ABOUT",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_ABOUT[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 243, 245, 243, 247, 247, 247, 255,
	/* bitmap (1, 0) */ 255, 27, 213, 189, 123, 127, 27, 255,
	/* bitmap (2, 0) */ 224, 224, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_EDIT",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_EDIT[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 137, 186, 138, 186, 186, 137, 255,
	/* bitmap (1, 0) */ 255, 136, 221, 221, 221, 221, 141, 255,
	/* bitmap (2, 0) */ 224, 224, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_CLEAR",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_CLEAR[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 242, 238, 238, 238, 238, 242, 255,
	/* bitmap (1, 0) */ 255, 231, 235, 231, 235, 235, 43, 255,
	/* bitmap (2, 0) */ 224, 224, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_BOX",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_BOX[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 231, 234, 230, 234, 234, 231, 255,
	/* bitmap (1, 0) */ 255, 107, 171, 183, 171, 171, 107, 255,
	/* bitmap (2, 0) */ 224, 224, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "MENU_HIDE",
   "width": 19,
   "height": 8
 }
*/

static const unsigned char MENU_HIDE[] = {
	/* width */ 19, /* height */ 8,
	/* bitmap (0, 0) */ 255, 168, 173, 141, 173, 173, 168, 255,
	/* bitmap (1, 0) */ 255, 152, 171, 168, 171, 171, 152, 255,
	/* bitmap (2, 0) */ 224, 224, 224, 224, 224, 192, 128, 0
};

/* #BITMAP_END */

/* #BITMAP_START */

/*
 {
   "variable_name": "ICON_16",
   "width": 16,
   "height": 16
 }
*/

static const unsigned char ICON_16[] = {
	/* width */ 16, /* height */ 16,
	/* bitmap (0, 0) */ 7, 24, 96, 129, 70, 32, 16, 16,
	/* bitmap (1, 0) */ 128, 64, 32, 144, 147, 143, 142, 156,
	/* bitmap (0, 1) */ 9, 9, 9, 25, 60, 60, 30, 7,
	/* bitmap (1, 1) */ 56, 116, 100, 130, 1, 6, 28, 248
};

/* #BITMAP_END */

#endif /* _BITMAPS_ */