import type { Bitmap } from '../types'

function pixelsToSpriteData(pixels: boolean[][], width: number, height: number): number[] {
  const cols = Math.ceil(width / 8)
  const rows = Math.ceil(height / 8)
  const totalBytes = cols * rows * 8
  const data = new Array(totalBytes).fill(0)

  for (let y = 0; y < height; y++) {
    const spriteRow = Math.floor(y / 8)
    const localY = y % 8
    for (let x = 0; x < width; x++) {
      const spriteCol = Math.floor(x / 8)
      const localX = x % 8
      const byteOffset = spriteRow * cols * 8 + spriteCol * 8 + localY
      const bitPos = 7 - localX
      if (pixels[y][x]) {
        data[byteOffset] |= 1 << bitPos
      }
    }
  }

  return data
}

export function exportHFile(bitmaps: Bitmap[], headerGuard: string, fileName: string): string {
  const lines: string[] = []

  lines.push(`#ifndef ${headerGuard}`)
  lines.push(`#define ${headerGuard}`)
  lines.push('')
  lines.push('/*')
  lines.push(` * ${fileName}`)
  lines.push(' * Auto-generated by Plotter-Z Bitmap Editor')
  lines.push(' * Do not remove BITMAP_START/BITMAP_END markers or JSON metadata')
  lines.push(' */')
  lines.push('')

  for (const bm of bitmaps) {
    const cols = Math.ceil(bm.width / 8)
    const rows = Math.ceil(bm.height / 8)
    const spriteData = pixelsToSpriteData(bm.pixels, bm.width, bm.height)

    const arrayLines: string[] = []
    arrayLines.push(`\t/* width */ ${bm.width}, /* height */ ${bm.height},`)

    for (let row = 0; row < rows; row++) {
      for (let col = 0; col < cols; col++) {
        const idx = row * cols + col
        const bytes = spriteData.slice(idx * 8, idx * 8 + 8)
        const byteStr = bytes.join(', ')
        arrayLines.push(`\t/* bitmap (${col}, ${row}) */ ${byteStr},`)
      }
    }

    const lastIdx = arrayLines.length - 1
    arrayLines[lastIdx] = arrayLines[lastIdx].replace(/,$/, '')

    const jsonStr = JSON.stringify(
      {
        variable_name: bm.name,
        width: bm.width,
        height: bm.height,
      },
      null,
      2
    )

    lines.push('/* #BITMAP_START */')
    lines.push('')
    lines.push('/*')
    lines.push(jsonStr.split('\n').map(line => ' ' + line).join('\n'))
    lines.push('*/')
    lines.push('')
    lines.push(`static const unsigned char ${bm.name}[] = {`)
    lines.push(...arrayLines)
    lines.push('};')
    lines.push('')
    lines.push('/* #BITMAP_END */')
    lines.push('')
  }

  lines.push(`#endif /* ${headerGuard} */`)

  return lines.join('\n')
}
